name: Node.js CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Run Lint (Optional)
      run: echo "No lint script defined"

    - name: Run Tests (Optional)
      run: echo "No tests defined"

    - name: Start App (for deployment or check)
      run: |
        nohup node index.js &
        sleep 5
        curl http://localhost:3000/health || exit 1
